const ACTIONS = {
  PROGRESS: "PROGRESS",
  STATISTICS_GET: "STATISTICS_GET",
  INSTANCE_GET: "INSTANCE_GET",
  INSTANCES_GET: "INSTANCES_GET",
  LOG: "LOG",
  EXPORT_ASSET: "EXPORT_ASSET",
  ROTATE_IMAGE: "ROTATE_IMAGE"
};
export default ACTIONS;
