const ACTIONS = {
  PROGRESS: "PROGRESS",
  STATISTICS_GET: "STATISTICS_GET",
  INSTANCE_GET: "INSTANCE_GET",
  INSTANCES_GET: "INSTANCES_GET",
  LOG: "LOG",
  EXPORT_ASSET: "EXPORT_ASSET",
  ROTATE_IMAGE: "ROTATE_IMAGE",
  PREFERENCES_GET: "PREFERENCES_GET",
  PREFERENCES_SET: "PREFERENCES_SET",
  PREFS_PATH: "PREFS_PATH",
  BULK_IMPORT: "BULK_IMPORT"
};
export default ACTIONS;
